spring.application.name=content

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/creatoros
spring.datasource.username=creatoros
spring.datasource.password=creatoros
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379